# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'import_dialog.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGroupBox, QHeaderView, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QSpinBox, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_ImportDialog(object):
    def setupUi(self, ImportDialog):
        if not ImportDialog.objectName():
            ImportDialog.setObjectName(u"ImportDialog")
        ImportDialog.resize(761, 651)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImportDialog.sizePolicy().hasHeightForWidth())
        ImportDialog.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(14)
        ImportDialog.setFont(font)
        ImportDialog.setLocale(QLocale(QLocale.Hungarian, QLocale.Hungary))
        self.ImportButton = QPushButton(ImportDialog)
        self.ImportButton.setObjectName(u"ImportButton")
        self.ImportButton.setGeometry(QRect(340, 610, 80, 34))
        font1 = QFont()
        font1.setPointSize(10)
        self.ImportButton.setFont(font1)
        self.FilePathLineEdit = QLineEdit(ImportDialog)
        self.FilePathLineEdit.setObjectName(u"FilePathLineEdit")
        self.FilePathLineEdit.setGeometry(QRect(80, 10, 581, 26))
        self.FilePathLineEdit.setFont(font1)
        self.FilePathLineEdit.setReadOnly(True)
        self.BrowseButton = QPushButton(ImportDialog)
        self.BrowseButton.setObjectName(u"BrowseButton")
        self.BrowseButton.setGeometry(QRect(670, 10, 81, 26))
        self.BrowseButton.setFont(font1)
        self.tableWidget = QTableWidget(ImportDialog)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(250, 50, 501, 551))
        font2 = QFont()
        font2.setPointSize(9)
        self.tableWidget.setFont(font2)
        self.FormatOptionsGroupBox = QGroupBox(ImportDialog)
        self.FormatOptionsGroupBox.setObjectName(u"FormatOptionsGroupBox")
        self.FormatOptionsGroupBox.setGeometry(QRect(10, 40, 231, 561))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        self.FormatOptionsGroupBox.setFont(font3)
        self.FormatOptionsGroupBox.setStyleSheet(u"")
        self.WavelengthRowLabel = QLabel(self.FormatOptionsGroupBox)
        self.WavelengthRowLabel.setObjectName(u"WavelengthRowLabel")
        self.WavelengthRowLabel.setGeometry(QRect(10, 350, 220, 26))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        self.WavelengthRowLabel.setFont(font4)
        self.OtherSepLabel = QLabel(self.FormatOptionsGroupBox)
        self.OtherSepLabel.setObjectName(u"OtherSepLabel")
        self.OtherSepLabel.setGeometry(QRect(10, 100, 200, 26))
        self.OtherSepLabel.setFont(font4)
        self.SepLabel = QLabel(self.FormatOptionsGroupBox)
        self.SepLabel.setObjectName(u"SepLabel")
        self.SepLabel.setGeometry(QRect(10, 30, 200, 26))
        self.SepLabel.setFont(font4)
        self.DecLabel = QLabel(self.FormatOptionsGroupBox)
        self.DecLabel.setObjectName(u"DecLabel")
        self.DecLabel.setGeometry(QRect(10, 170, 200, 26))
        self.DecLabel.setFont(font4)
        self.SepComboBox = QComboBox(self.FormatOptionsGroupBox)
        self.SepComboBox.addItem("")
        self.SepComboBox.addItem("")
        self.SepComboBox.addItem("")
        self.SepComboBox.addItem("")
        self.SepComboBox.addItem("")
        self.SepComboBox.addItem("")
        self.SepComboBox.addItem("")
        self.SepComboBox.addItem("")
        self.SepComboBox.addItem("")
        self.SepComboBox.setObjectName(u"SepComboBox")
        self.SepComboBox.setGeometry(QRect(10, 60, 200, 31))
        self.SepComboBox.setFont(font4)
        self.OtherSepLineEdit = QLineEdit(self.FormatOptionsGroupBox)
        self.OtherSepLineEdit.setObjectName(u"OtherSepLineEdit")
        self.OtherSepLineEdit.setGeometry(QRect(10, 130, 200, 31))
        self.OtherSepLineEdit.setFont(font4)
        self.OtherSepLineEdit.setMaxLength(32767)
        self.WaveIsRowCheckBox = QCheckBox(self.FormatOptionsGroupBox)
        self.WaveIsRowCheckBox.setObjectName(u"WaveIsRowCheckBox")
        self.WaveIsRowCheckBox.setGeometry(QRect(10, 240, 200, 31))
        self.WaveIsRowCheckBox.setFont(font4)
        self.TimeColumnLabel = QLabel(self.FormatOptionsGroupBox)
        self.TimeColumnLabel.setObjectName(u"TimeColumnLabel")
        self.TimeColumnLabel.setGeometry(QRect(10, 280, 220, 26))
        self.TimeColumnLabel.setFont(font4)
        self.TimeColumnSpinBox = QSpinBox(self.FormatOptionsGroupBox)
        self.TimeColumnSpinBox.setObjectName(u"TimeColumnSpinBox")
        self.TimeColumnSpinBox.setGeometry(QRect(10, 310, 201, 31))
        self.TimeColumnSpinBox.setFont(font4)
        self.TimeColumnSpinBox.setMinimum(1)
        self.TimeColumnSpinBox.setMaximum(999)
        self.TimeColumnSpinBox.setValue(1)
        self.WavelengthRowSpinBox = QSpinBox(self.FormatOptionsGroupBox)
        self.WavelengthRowSpinBox.setObjectName(u"WavelengthRowSpinBox")
        self.WavelengthRowSpinBox.setGeometry(QRect(10, 380, 201, 31))
        self.WavelengthRowSpinBox.setFont(font4)
        self.WavelengthRowSpinBox.setMinimum(1)
        self.WavelengthRowSpinBox.setMaximum(999)
        self.WavelengthRowSpinBox.setValue(1)
        self.DecComboBox = QComboBox(self.FormatOptionsGroupBox)
        self.DecComboBox.addItem("")
        self.DecComboBox.addItem("")
        self.DecComboBox.setObjectName(u"DecComboBox")
        self.DecComboBox.setGeometry(QRect(10, 200, 200, 31))
        self.DecComboBox.setFont(font4)
        self.TimeMetricComboBox = QComboBox(self.FormatOptionsGroupBox)
        self.TimeMetricComboBox.addItem("")
        self.TimeMetricComboBox.addItem("")
        self.TimeMetricComboBox.addItem("")
        self.TimeMetricComboBox.addItem("")
        self.TimeMetricComboBox.addItem("")
        self.TimeMetricComboBox.setObjectName(u"TimeMetricComboBox")
        self.TimeMetricComboBox.setGeometry(QRect(10, 450, 201, 31))
        self.TimeMetricComboBox.setFont(font4)
        self.TimeMetricLabel = QLabel(self.FormatOptionsGroupBox)
        self.TimeMetricLabel.setObjectName(u"TimeMetricLabel")
        self.TimeMetricLabel.setGeometry(QRect(10, 420, 201, 26))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setKerning(True)
        self.TimeMetricLabel.setFont(font5)
        self.WavelengthMetricLabel = QLabel(self.FormatOptionsGroupBox)
        self.WavelengthMetricLabel.setObjectName(u"WavelengthMetricLabel")
        self.WavelengthMetricLabel.setGeometry(QRect(10, 490, 201, 26))
        self.WavelengthMetricLabel.setFont(font4)
        self.WavelengthMetricComboBox = QComboBox(self.FormatOptionsGroupBox)
        self.WavelengthMetricComboBox.addItem("")
        self.WavelengthMetricComboBox.addItem("")
        self.WavelengthMetricComboBox.addItem("")
        self.WavelengthMetricComboBox.setObjectName(u"WavelengthMetricComboBox")
        self.WavelengthMetricComboBox.setGeometry(QRect(10, 520, 201, 31))
        self.WavelengthMetricComboBox.setFont(font4)
        self.FilePathLabel = QLabel(ImportDialog)
        self.FilePathLabel.setObjectName(u"FilePathLabel")
        self.FilePathLabel.setGeometry(QRect(10, 10, 71, 26))
        self.FilePathLabel.setFont(font1)

        self.retranslateUi(ImportDialog)

        QMetaObject.connectSlotsByName(ImportDialog)
    # setupUi

    def retranslateUi(self, ImportDialog):
        ImportDialog.setWindowTitle(QCoreApplication.translate("ImportDialog", u"Import ablak", None))
        self.ImportButton.setText(QCoreApplication.translate("ImportDialog", u"Import\u00e1l\u00e1s", None))
        self.BrowseButton.setText(QCoreApplication.translate("ImportDialog", u"Tall\u00f3z\u00e1s...", None))
        self.FormatOptionsGroupBox.setTitle(QCoreApplication.translate("ImportDialog", u"Import\u00e1l\u00e1si be\u00e1ll\u00edt\u00e1sok", None))
        self.WavelengthRowLabel.setText(QCoreApplication.translate("ImportDialog", u"Hull\u00e1mhosszat tartalmaz\u00f3 sor/oszlop:", None))
        self.OtherSepLabel.setText(QCoreApplication.translate("ImportDialog", u"Egy\u00e9ni Szepar\u00e1tor:", None))
        self.SepLabel.setText(QCoreApplication.translate("ImportDialog", u"Szepar\u00e1tor karakter (tippelt):", None))
        self.DecLabel.setText(QCoreApplication.translate("ImportDialog", u"Tizedesjel:", None))
        self.SepComboBox.setItemText(0, QCoreApplication.translate("ImportDialog", u"Pontos vessz\u0151 (;)", None))
        self.SepComboBox.setItemText(1, QCoreApplication.translate("ImportDialog", u"Kett\u0151spont (:)", None))
        self.SepComboBox.setItemText(2, QCoreApplication.translate("ImportDialog", u"Vessz\u0151 (,)", None))
        self.SepComboBox.setItemText(3, QCoreApplication.translate("ImportDialog", u"Tabul\u00e1tor (\\t)", None))
        self.SepComboBox.setItemText(4, QCoreApplication.translate("ImportDialog", u"K\u00f6t\u0151jel (-)", None))
        self.SepComboBox.setItemText(5, QCoreApplication.translate("ImportDialog", u"Al\u00e1h\u00faz\u00e1s (_)", None))
        self.SepComboBox.setItemText(6, QCoreApplication.translate("ImportDialog", u"Sz\u00f3k\u00f6z ( )", None))
        self.SepComboBox.setItemText(7, QCoreApplication.translate("ImportDialog", u"F\u00fcgg\u0151leges vonal (|)", None))
        self.SepComboBox.setItemText(8, QCoreApplication.translate("ImportDialog", u"Egy\u00e9ni", None))

#if QT_CONFIG(tooltip)
        self.SepComboBox.setToolTip(QCoreApplication.translate("ImportDialog", u"Ignor\u00e1lt, ha van valami bele\u00edrva az egy\u00e9b szepar\u00e1tor men\u00fcbe.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.OtherSepLineEdit.setToolTip(QCoreApplication.translate("ImportDialog", u"A list\u00e1ban nem tal\u00e1lhat\u00f3 szepar\u00e1tor eset\u00e9n kell kit\u00f6lteni.", None))
#endif // QT_CONFIG(tooltip)
        self.WaveIsRowCheckBox.setText(QCoreApplication.translate("ImportDialog", u"A sorok a hull\u00e1mok?", None))
        self.TimeColumnLabel.setText(QCoreApplication.translate("ImportDialog", u"Id\u0151b\u00e9lyeget tartalmaz\u00f3 sor/oszlop:", None))
#if QT_CONFIG(tooltip)
        self.TimeColumnSpinBox.setToolTip(QCoreApplication.translate("ImportDialog", u"H\u00e1nyadik sor/oszlop tartalmazza az id\u0151 b\u00e9lyeget.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.WavelengthRowSpinBox.setToolTip(QCoreApplication.translate("ImportDialog", u"H\u00e1nyadik sor/oszlop tartalmazza a hull\u00e1mhosszat.", None))
#endif // QT_CONFIG(tooltip)
        self.DecComboBox.setItemText(0, QCoreApplication.translate("ImportDialog", u"Pont (.)", None))
        self.DecComboBox.setItemText(1, QCoreApplication.translate("ImportDialog", u"Vessz\u0151 (,)", None))

#if QT_CONFIG(tooltip)
        self.DecComboBox.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.TimeMetricComboBox.setItemText(0, QCoreApplication.translate("ImportDialog", u"Nanosecond (ns)", None))
        self.TimeMetricComboBox.setItemText(1, QCoreApplication.translate("ImportDialog", u"Microsecond (\u03bcs)", None))
        self.TimeMetricComboBox.setItemText(2, QCoreApplication.translate("ImportDialog", u"Picosecond (ps)", None))
        self.TimeMetricComboBox.setItemText(3, QCoreApplication.translate("ImportDialog", u"Femtosecond (fs)", None))
        self.TimeMetricComboBox.setItemText(4, QCoreApplication.translate("ImportDialog", u"Attosecond (as)", None))

        self.TimeMetricLabel.setText(QCoreApplication.translate("ImportDialog", u"Id\u0151 m\u00e9rt\u00e9kegys\u00e9ge:", None))
        self.WavelengthMetricLabel.setText(QCoreApplication.translate("ImportDialog", u"Hull\u00e1mhossz m\u00e9rt\u00e9kegys\u00e9ge:", None))
        self.WavelengthMetricComboBox.setItemText(0, QCoreApplication.translate("ImportDialog", u"Nanometer (nm)", None))
        self.WavelengthMetricComboBox.setItemText(1, QCoreApplication.translate("ImportDialog", u"Micrometer (\u00b5m)", None))
        self.WavelengthMetricComboBox.setItemText(2, QCoreApplication.translate("ImportDialog", u"Picometer (pm)", None))

        self.FilePathLabel.setText(QCoreApplication.translate("ImportDialog", u"F\u00e1jl Helye:", None))
    # retranslateUi

